CrudMVC/CrudMVC/Models/ErrorViewModel.cs
namespace CrudMVC.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

CrudMVC/CrudMVC/Models/PokeType.cs
namespace CrudMVC.Models
{
	public class PokeType
	{
		public int Id { get; set; }
		public string Name { get; set; }
		// EF NAVIGATION

		public List<Pokemon>? Pokemons { get; set; }
	}
}

CrudMVC/CrudMVC/Models/Pokemon.cs
namespace CrudMVC.Models
{
	public class Pokemon
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public int PokeTypeId { get; set; }
		public PokeType PokemonType { get; set; }
		public Pokemon()
		{

		}
		public Pokemon(int id, string name, int pokeTypeId)
		{
			Id = id;
			Name = name;
			PokeTypeId = pokeTypeId;
		}
	}
}

CrudMVC/CrudMVC/Models/PokemonContext.cs
using Microsoft.EntityFrameworkCore;

namespace CrudMVC.Models
{
	public class PokemonContext : DbContext
	{
		public PokemonContext(DbContextOptions optionsBuilder) : base(optionsBuilder) { }
		public DbSet<Pokemon> Pokemons { get; set; }
		public DbSet<PokeType> Types { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			if (!optionsBuilder.IsConfigured)
			{
				optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=PokemonDb;Trusted_Connection=True;");
			}
			base.OnConfiguring(optionsBuilder);
		}
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{

			PokeType poison = new PokeType { Id = 1, Name = "poison" };
			Pokemon Oulou = new Pokemon(1, "oulou", 1);
			
			modelBuilder.Entity<PokeType>().HasData(poison);
			modelBuilder.Entity<Pokemon>().HasData(Oulou);
			base.OnModelCreating(modelBuilder);
			
		}
	}
}

CrudMVC/CrudMVC/Controllers/HomeController.cs
using CrudMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudMVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

CrudMVC/CrudMVC/Controllers/PartialController.cs
using Microsoft.AspNetCore.Mvc;

namespace CrudMVC.Controllers
{
	public class PartialController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Create()
		{
			return PartialView("_PartialCreate");
		}
	}
}

CrudMVC/CrudMVC/Controllers/PokemonsController.cs
using CrudMVC.Models;
using CrudMVC.Repository;
using Microsoft.AspNetCore.Mvc;

namespace CrudMVC.Controllers
{
	public class PokemonsController : Controller
	{
		private readonly PokemonContext context;
		private readonly PokemonRepository pokemonRepository;
		private readonly TypeRepository typeRepository;
		public PokemonsController(PokemonContext context, PokemonRepository repository, TypeRepository typeRepository)
		{
			this.context = context;
			this.pokemonRepository = repository;
			this.typeRepository = typeRepository;
		}
		public IActionResult Index()
		{
			return View();
		}
		public async Task<IActionResult> Get(int id)
		{
			ViewBag.Message = "Viewbag Message";
			return View(await this.pokemonRepository.Get(id));
		}
		[HttpGet]
		public async Task<IActionResult> Create()
		{
			return View(await typeRepository.GetAll());
		}
		[HttpPost]
		public async Task<IActionResult> Create(Pokemon pokemon)
		{
			try
			{
				await pokemonRepository.Create(pokemon);
				ViewBag.Message = "Create Reussis";
				return View();
			}catch (Exception ex)
			{
				ViewBag.Message = ex.Message;
				return View();
			}
		}
		[HttpGet]
		public async Task<IActionResult> GetAll()
		{
			return View(await  pokemonRepository.GetAll());
		}
	}
}

CrudMVC/CrudMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a asp-controller="Pokemons" asp-action="Get" asp-route-id="1">rzqedr</a>
</div>

CrudMVC/CrudMVC/Views/Partial/Index.cshtml
<partial name="_PartialCreate" />

CrudMVC/CrudMVC/Views/Pokemons/Create.cshtml
@model List<PokeType>

<div>
	@if (@ViewBag.Message == null)
	{
		<form asp-action="Create">
			<input name="id" hidden />
			<label> NOM du pokemon</label>
			<input name="name" id="Name" />
			<label> Type du pokemon</label>
			@* <input name="pokeTypeId"/> *@
			<select name="pokeTypeId">
				@foreach (var item in @Model)
				{
					<option value="@item.Id"> @item.Name </option>
				}
			</select>
			<button type="submit"> Submit </button>
		</form>
	}
	else
	{
		<h1> @ViewBag.Message </h1>
	}
</div>

CrudMVC/CrudMVC/Views/Pokemons/Get.cshtml
@model Pokemon


<div class="container-fluid d-flex flex-column justify-content-center align-items-center full-height">
    <h1 id="PokemonName" class="h1"> NOM : @Model.Name @ViewBag.Message </h1>
    <h2 id="PokemonId"> Id : @Model.Id  </h2>
    <h2 id="PokemonType"> PokeTypeId : @Model.PokeTypeId </h2>
</div>

CrudMVC/CrudMVC/Views/Pokemons/GetAll.cshtml
@model List<Pokemon>

<style>
	.pokedex-container {
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
		gap: 15px;
	}

	.pokemon-card {
		border: 1px solid #ccc;
		padding: 15px;
		border-radius: 8px;
		text-align: center;
	}
</style>
<div class="container">
	<h1 class="text-center my-4"> POKEDEX </h1>
	<div class="pokedex-container">
		@foreach (var item in Model)
		{
			<div class="pokemon-card">
				<h2> Nom : @item.Name </h2>
				<p> PokeId : @item.Id</p>
				<p> TypeId : @item.PokeTypeId </p>
			</div>
		}
	</div>
</div>

CrudMVC/CrudMVC/Views/Pokemons/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div>
    <p> CREATE </p>
</div>

CrudMVC/CrudMVC/Views/Shared/Components/Create/Default.cshtml
@model List<PokeType>

	<option> TEST </option>
@foreach (var item in @Model)
{
	<option value="@item.Id"> @item.Name </option>
}

CrudMVC/CrudMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemons" asp-action="Get">Pokemons</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CrudMVC/CrudMVC/Views/Shared/_PartialCreate.cshtml
@model List<PokeType>

<form asp-action="Create" asp-controller="Pokemons">
	<input name="id" hidden />
	<label> NOM du pokemon</label>
	<input name="name" id="Name" />
	<label> Type du pokemon</label>
	@* <input name="pokeTypeId"/> *@
	<select name="pokeTypeId">
		<option value=""> Selectionnez un Type </option>
		  @* @await Component.InvokeAsync("Create") *@
		 <vc:Create></vc:Create>
	</select>
	<button type="submit"> Submit </button>
</form>